export const stageDefine = {
    0: {
        GRID_X: 6,
        GRID_Y: 10,
        ELEMENT_RANGE: 6,
        isStaticBlock(i: number, j: number) { return false },
        isEmptyBlock(i: number, j: number) { return false },
        timeLimit: 600,
        goldAquirement: 1,
        BLOCK_WIDTH: 60,
        RADIO: 1.2,
    },
    1: {
        GRID_X: 8,
        GRID_Y: 12,
        ELEMENT_RANGE: 10,
        isStaticBlock(i: number, j: number) { return false },
        isEmptyBlock(i: number, j: number) { return false },
        timeLimit: 480,
        goldAquirement: 2,
        BLOCK_WIDTH: 50,
        RADIO: 1,
    },
    2: {
        GRID_X: 10,
        GRID_Y: 14,
        ELEMENT_RANGE: 14,
        isStaticBlock(i: number, j: number) { return false },
        isEmptyBlock(i: number, j: number) { return Math.random() < 0.2 },
        timeLimit: 300,
        goldAquirement: 3,
        BLOCK_WIDTH: 50,
        RADIO: 1,
    },
    3: {
        GRID_X: 10,
        GRID_Y: 14,
        ELEMENT_RANGE: 18,
        isStaticBlock(i: number, j: number) { return false },
        isEmptyBlock(i: number, j: number) { return Math.random() < 0.1 },
        timeLimit: 300,
        goldAquirement: 4,
        BLOCK_WIDTH: 50,
        RADIO: 1,
    },
    4: {
        GRID_X: 10,
        GRID_Y: 14,
        ELEMENT_RANGE: 22,
        isStaticBlock(i: number, j: number) { return false },
        isEmptyBlock(i: number, j: number) { return false },
        timeLimit: 240,
        goldAquirement: 5,
        BLOCK_WIDTH: 50,
        RADIO: 1,
    },
    5: {
        GRID_X: 10,
        GRID_Y: 14,
        ELEMENT_RANGE: 22,
        isStaticBlock(i: number, j: number) { return false },
        isEmptyBlock(i: number, j: number) { return false },
        timeLimit: 210,
        goldAquirement: 6,
        BLOCK_WIDTH: 50,
        RADIO: 1,
    },
    6: {
        GRID_X: 12,
        GRID_Y: 16,
        ELEMENT_RANGE: 26,
        isStaticBlock(i: number, j: number) { return false },
        isEmptyBlock(i: number, j: number) { return Math.random() < 0.3 },
        timeLimit: 180,
        goldAquirement: 7,
        BLOCK_WIDTH: 40,
        RADIO: 0.8,
    },
    7: {
        GRID_X: 12,
        GRID_Y: 16,
        ELEMENT_RANGE: 26,
        isStaticBlock(i: number, j: number) { return false },
        isEmptyBlock(i: number, j: number) { return Math.random() < 0.2 },
        timeLimit: 180,
        goldAquirement: 8,
        BLOCK_WIDTH: 40,
        RADIO: 0.8,
    },
    8: {
        GRID_X: 12,
        GRID_Y: 16,
        ELEMENT_RANGE: 26,
        isStaticBlock(i: number, j: number) { return false },
        isEmptyBlock(i: number, j: number) { return Math.random() < 0.1 },
        timeLimit: 180,
        goldAquirement: 9,
        BLOCK_WIDTH: 40,
        RADIO: 0.8,
    },
    9: {
        GRID_X: 12,
        GRID_Y: 16,
        ELEMENT_RANGE: 26,
        isStaticBlock(i: number, j: number) { return false },
        isEmptyBlock(i: number, j: number) { return false },
        timeLimit: 180,
        goldAquirement: 10,
        BLOCK_WIDTH: 40,
        RADIO: 0.8,
    },
    10: {
        GRID_X: 12,
        GRID_Y: 16,
        ELEMENT_RANGE: 26,
        isStaticBlock(i: number, j: number) { return i === 7 && j > 3 && j < 8 },
        isEmptyBlock(i: number, j: number) { return false },
        timeLimit: 180,
        goldAquirement: 11,
        BLOCK_WIDTH: 40,
        RADIO: 0.8,
    },
    11: {
        GRID_X: 12,
        GRID_Y: 16,
        ELEMENT_RANGE: 26,
        isStaticBlock(i: number, j: number) { return Math.random() < 0.1 },
        isEmptyBlock(i: number, j: number) { return false },
        timeLimit: 150,
        goldAquirement: 12,
        BLOCK_WIDTH: 40,
        RADIO: 0.8,
    }
}